routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::resource('/users', 'UsersController');
    Route::resource('/roles', 'RolesController');
    Route::resource('/maintenance-payments', 'MaintenancePaymentsController');
    Route::resource('/payments', 'PaymentsController');
    Route::resource('/schedules', 'SchedulesController');

});

Route::get('/home', 'HomeController@index')->name('home');

app/MaintenancePayment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MaintenancePayment extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }
}

app/Http/Controllers/MaintenancePaymentsController.php
<?php

namespace App\Http\Controllers;

use App\MaintenancePayment;
use App\User;
use Illuminate\Http\Request;

class MaintenancePaymentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['payments'] = MaintenancePayment::all();

        return view('maintenance_payments.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['users'] = User::all();

        return view('maintenance_payments.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $payment = new MaintenancePayment();
        $payment->concept = $request->concept;
        $payment->quantity = $request->quantity;
        $payment->status = $request->status;
        $payment->user_id = $request->user;
        $payment->save();

        return redirect()->route('maintenance-payments.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(MaintenancePayment $maintenance_payment)
    {
        $data['payment'] = $maintenance_payment;

        return view('maintenance_payments.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, MaintenancePayment $maintenance_payment)
    {
        $maintenance_payment->concept = $request->concept;
        $maintenance_payment->quantity = $request->quantity;
        $maintenance_payment->status = $request->status;
        $maintenance_payment->save();

        return redirect()->route('maintenance-payments.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(MaintenancePayment $maintenance_payment)
    {
        $maintenance_payment->delete();

        return redirect()->route('maintenance-payments.index');
    }
}

resources/views/maintenance_payments/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">
            <h1 class="text-center"> Crear Pago</h1>
        </div>
        <div class="card-body">
            <form action="{{route('maintenance-payments.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="concept">Concepto</label>
                    <input type="text" class="form-control" id="concept" name="concept" placeholder="Escribe el valor"  required>
                </div>
                <div class="form-group">
                    <label for="quantity">Cantidad</label>
                    <input type="number" class="form-control" id="quantity" name="quantity" placeholder="Escribe el valor" required>
                </div>
                <div class="form-group">
                    <label for="status">Estatus</label>
                    <select name="status" id="status" class="form-control">
                        <option value="C">Completado</option>
                        <option value="O">No Completado</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="status">Usuario</label>
                    <select name="user" id="status" class="form-control">
                        @foreach($users as $user)
                            <option value="{{$user->id}}">{{$user->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <button class="btn btn-info" type="submit">Agregar</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/maintenance_payments/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">
            <h1 class="text-center"> Editar Pago</h1>
        </div>
        <div class="card-body">
            <form action="{{route('maintenance-payments.update',$payment->id)}}" method="post">
                @csrf
                @method('put')
                <div class="form-group">
                    <label for="concept">Concepto</label>
                    <input type="text" class="form-control" id="concept" name="concept" placeholder="Escribe el valor" value="{{$payment->concept}}" readonly>
                </div>
                <div class="form-group">
                    <label for="quantity">Cantidad</label>
                    <input type="number" class="form-control" id="quantity" name="quantity" placeholder="Escribe el valor" value="{{$payment->quantity}}" readonly>
                </div>
                <div class="form-group">
                    <label for="status">Estatus</label>
                    <select name="status" id="status">
                        <option value="C">Completado</option>
                        <option value="O">No Completado</option>
                    </select>
                </div>
                <div class="form-group">
                    <button class="btn btn-info" type="submit">Editar</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/maintenance_payments/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <table id="payment-table">
            <thead>
            <tr>
                <th scope="col">Concepto</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Estatus</th>
                <th scope="col">Usuario</th>
                <th scope="col">Acciones</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($payments as $payment )
                <tr>
                    <th scope="row">{{ $payment->concept }}</th>
                    <th scope="row">{{ $payment->quantity }}</th>
                    <th scope="row">{{ $payment->status == 'C' ? 'Completado' : 'No Completado' }}</th>
                    <th scope="row">{{ $payment->user ? $payment->user->name :'N/A' }}</th>
                    <td>
                        @if (Auth::user()->role_id == 1)
                            <a href="{{route('maintenance-payments.edit',$payment->id)}}" class="btn btn-warning btn-sm">Editar</a>
                            <button data-toggle="modal" data-target="#exampleModal" data-id="{{$payment->id}}" class="btn btn-danger btn-sm eliminar">Eliminar</button>
                        @else
                            <p>N/A</p>
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>


    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Eliminar Pago</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5>Seguro que deseas eliminar</h5>
                    <form id="form-delete" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">Si</button>
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            $(document).ready( function () {
                $('#payment-table').DataTable();

                $('.eliminar').click(function () {
                    let id = $(this).data('id')
                    $('#form-delete').attr('action', '/maintenance-payments/'+ id);
                })
            } );
        </script>
    @endpush

@endsection