routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::resource('/users', 'UsersController');
    Route::resource('/roles', 'RolesController');
    Route::resource('/maintenance-payments', 'MaintenancePaymentsController');
    Route::resource('/payments', 'PaymentsController');
    Route::resource('/schedules', 'SchedulesController');

});

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/includes/header.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="btn btn-info">
            <i class="fas fa-align-left"></i>
        </button>
        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-align-justify"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
                    <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        Logout
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/includes/sidebar.blade.php
<nav id="sidebar">
    <div class="sidebar-header">
        <h3>Fraccionamiento</h3>
    </div>
    @auth
        <ul class="list-unstyled components">
            <p class="text-center">{{ Auth::user()->name }}</p>
            @if (Auth::user()->role_id == 1)
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Usuarios</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{{route('users.index')}}">Lista</a>
                        </li>
                        <li>
                            <a href="{{route('users.create')}}">Crear</a>
                        </li>
                    </ul>
                </li>
            @endif


            <li class="active">
                <a href="#pay-m" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pagos Mantenimiento</a>
                <ul class="collapse list-unstyled" id="pay-m">
                    <li>
                        <a href="{{route('maintenance-payments.index')}}">Lista</a>
                    </li>
                    <li>
                        <a href="{{route('maintenance-payments.create')}}">Crear</a>
                    </li>
                </ul>
            </li>
            <li class="active">
                <a href="#pay" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pagos</a>
                <ul class="collapse list-unstyled" id="pay">
                    <li>
                        <a href="{{route('payments.index')}}">Lista</a>
                    </li>
                    @if (Auth::user()->role_id == 1)
                        <li>
                            <a href="{{route('payments.create')}}">Crear</a>
                        </li>
                    @endif

                </ul>
            </li>
            <li class="active">
                <a href="#schedule" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Reservaciones</a>
                <ul class="collapse list-unstyled" id="schedule">
                    <li>
                        <a href="{{route('schedules.index')}}">Lista</a>
                    </li>
                    <li>
                        <a href="{{route('schedules.create')}}">Crear</a>
                    </li>
                </ul>
            </li>
        </ul>
    @endauth

</nav>